ARG BASE
FROM ${BASE}

WORKDIR /app
COPY python python
COPY EulerOS.repo /etc/yum.repos.d/
COPY kmc-adapter /kmc/kmc-adapter
COPY root /var/spool/cron/

RUN ln -s /usr/lib64/libpython3.9.so.1.0 /usr/lib64/libpython3.9.so

RUN echo $(python3 --version)
RUN echo $(python --version)

COPY ./fit_start.sh /app/python/fit_start.sh

RUN yum makecache && \
    yum install -y shadow-utils logrotate cronie python3-pip && \
    rm -rf /etc/yum.repos.d/EulerOS.repo && \
    groupadd -g 1300 -r runtime && \
    groupadd -g 2000 -r appengine && \
    useradd -u 1300 -r -g 1300 -G 2000 -M runtime && \
    useradd -r -g appengine -G 2000 -M -u 201 modelenginepublic && \
    cp /etc/cron.daily/logrotate /etc/cron.hourly/ && \
    chmod 700 /app/python/fit_start.sh && \
    useradd -u 200 -r -g 2000 -M fit

RUN mkdir -p /home/runtime/ && \
    chown -R runtime:runtime /home/runtime/ && \
    chown -R runtime:runtime /app/python/

ENV PATH="/home/runtime/.local/bin:$PATH"
ENV PYTHONPATH="/home/runtime/.local/lib/python3.9/site-packages/:$PYTHONPATH"
WORKDIR /app/python
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/&& \
    pip3 config set global.trusted-host mirrors.aliyun.com && \
    pip3 install -r requirements.txt && \
    pip3 install -r fel-requirements.txt && \
    pip3 install pandas==2.1.3 mysql-connector-python pymysql==1.1.0 elasticsearch==7.17.12 cryptography

USER root

WORKDIR /app/python
RUN rm -rf /app/databus_python_sdk \
    && chown -R 1300:2000 /kmc/kmc-adapter \
    && bash /kmc/kmc-adapter/install.sh false \
    && rm -rf /kmc/kmc-adapter/kmc-lib.tar.gz

RUN chmod +x fit_start.sh
ENTRYPOINT ["./fit_start.sh"]
